#!/bin/bash

input=ssh-extra-accounts.txt
log=/tmp/ssh-accounts.log
pub=/home/razvan/.ssh/id_rsa_new.pub
priv=/home/razvan/.ssh/id_rsa_new

declare -a hosts
declare -a users

n=0
while read hostname username; do
	hosts["$n"]="$hostname"
	users["$n"]="$username"
	((n++))
done < "$input"

> $log
for ((i=0; i < $n; i++)); do
	echo -n "Adding ${users[$i]}@${hosts[$i]}..."
	cat "$pub" | ssh -l root "${hosts[$i]}" "eval cat - >> ~${users[$i]}/.ssh/authorized_keys"
	echo "done"
done
