#!/bin/bash

#OFFLINEIMAP=/opt/local/bin/offlineimap
OFFLINEIMAP=/usr/bin/offlineimap
LOGFILE=~/.log/offlineimap-cron.log

function check_alive()
{
	ps -ef | grep "$OFFLINEIMAP" | grep -v grep > /dev/null 2>&1
}

check_alive
if test $? -ne 0; then
	nohup ionice -c 3 -n 19 python2 "$OFFLINEIMAP" >> "$LOGFILE" 2>&1 &
fi

exit 0
