#!/bin/bash

mount_point=/live/image

# copy SSH keys
mkdir ~/.ssh
cp $mount_point/rd-ssh/* ~/.ssh
chmod 644 ~/.ssh/id_rsa.pub
chmod 600 ~/.ssh/id_rsa

sudo bash -c "cat > /etc/apt/sources.list" <<END
# /etc/apt/sources.list

deb http://ftp.lug.ro/debian/ squeeze main contrib non-free
deb http://ftp.lug.ro/debian/ squeeze-updates main contrib non-free
deb http://security.debian.org/ squeeze/updates main contrib non-free
END

sudo apt-get update
sudo apt-get install -y vim git flashplugin-nonfree
sudo cp /usr/share/vim/vim72/vimrc_example.vim /etc/vim/vimrc
sudo update-alternatives --set editor /usr/bin/vim.basic

git clone razvan@swarm.cs.pub.ro:git-repos/code.git && (
mkdir -p ~/.vim/bkup
ln -sf ~/code/config/vim/vimrc ~/.vimrc
ln -sf ~/code/config/vim/ftplugin ~/.vim/
ln -sf code/config/bash/bash_aliases ~/.bash_aliases
ln -sf code/config/emacs/emacs ~/.emacs
)

git config --global user.name "Razvan Deaconescu"
git config --global user.email "razvan.deaconescu@cs.pub.ro"
git config --global color.ui auto

echo "Europe/Bucharest" | sudo tee /etc/timezone > /dev/null
sudo dpkg-reconfigure -f noninteractive tzdata

> /dev/null sudo tee /etc/profile <<END

# Set LC_COLLATE="C". File system entries starting with capital are
# printed out first in a directory listing.
export LC_COLLATE="C"
END

cat /etc/profile <<END

# Set CDPATH to easily browse common folders.
export CDPATH=.:$HOME/school/current:$HOME/projects
END

gconftool-2 --set /apps/gnome-terminal/profiles/Default/cursor_blink_mode --type string off
gconftool-2 --set /apps/panel/toplevels/bottom_panel_screen0/auto_hide --type bool true
gconftool-2 --set /apps/panel/toplevels/top_panel_screen0/auto_hide --type bool true
gconftool-2 --set /apps/metacity/global_keybindings/run_command_terminal --type string "<Control><Alt>t"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/scrollbar_position --type string "hidden"
gconftool-2 --set /apps/gnome-terminal/profiles/Default/default_show_menubar --type bool false
gconftool-2 --set /apps/nautilus/preferences/always_use_browser --type bool true
gconftool-2 --set /apps/metacity/keybinding_commands/command_1 --type string --type string "/usr/bin/nautilus --browser"
gconftool-2 --set /apps/metacity/global_keybindings/run_command_1 --type string "<Control><Alt>b"
gconftool-2 --set /apps/metacity/keybinding_commands/command_2 --type string --type string "/usr/bin/x-www-browser"
gconftool-2 --set /apps/metacity/global_keybindings/run_command_2 --type string "<Control><Alt>w"
gconftool-2 --set /apps/metacity/keybinding_commands/command_3 --type string --type string "/usr/bin/evolution"
gconftool-2 --set /apps/metacity/global_keybindings/run_command_3 --type string "<Control><Alt>e"

cat > ~/.inputrc <<END
set show-all-if-ambiguous On
set completion-ignore-case On
END
