#!/bin/bash

sudo apt-get -y install less htop zip unzip vim vim-nox git subversion lsof libarchive-tools
sudo apt-get -y install build-essential electric-fence gdb cscope exuberant-ctags
sudo apt-get -y install strace ltrace valgrind
sudo apt-get -y install gawk
sudo apt-get -y install bash-completion
sudo apt-get -y install expect
sudo apt-get -y install netcat-traditional telnet pppoeconf host lynx curl ncftp
sudo apt-get -y install openssh-server smbclient cifs-utils ldap-utils
sudo apt-get -y install finger pciutils usbutils lshw mc clusterssh tree
sudo apt-get -y install tree ncal
sudo apt-get -y install wget curl lynx links elinks
# 200MB for texlive-latex-base, >800MB after texlive-latex-extra
sudo apt-get -y install texlive-latex-base texlive-latex-extra texlive-bibtex-extra texlive-publishers highlight
sudo apt-get -y install apt-file
sudo apt-get -y install wodim genisoimage
# 1.7GB
sudo apt-get -y install gnome
# 533MB
sudo apt-get -y install libreoffice
sudo apt-get -y install mplayer2 module-assistant
sudo apt-get -y install vim-gui-common nautilus-open-terminal deluge wbar
sudo apt-get -y install gitk hexchat pidgin dia
sudo apt-get -y install aspell-ro
sudo apt-get -y install wireless-tools tcpdump nmap
# non-free required
sudo apt-get -y install manpages-posix manpages-posix-dev make-doc glibc-doc-reference
# pwgen
sudo apt-get -y install pwgen
# lshw
sudo apt-get -y install lshw
# emacs, org-mode
sudo apt-get -y install emacs org-mode emacs-goodies-el
sudo apt-get -y install screen tmux
sudo apt-get -y install ethtool net-tools
# i3
sudo apt-get -y install i3
# dev
sudo apt-get -y install gcc-aarch64-linux-gnu
sudo apt-get -y install flex bison build-essential libncurses5-dev qemu-system-x86 qemu-system-arm python3 python-is-python3 minicom
