#!/bin/bash

sudo apt-get -y install less htop zip unzip vim-nox git subversion lsof
sudo apt-get -y install build-essential electric-fence gdb cscope exuberant-ctags
sudo apt-get -y install strace ltrace valgrind
sudo apt-get -y install gawk
sudo apt-get -y install bash-completion
sudo apt-get -y install expect
sudo apt-get -y install netcat telnet pppoeconf host lynx curl ncftp
sudo apt-get -y install openssh-server smbclient cifs-utils ldap-utils
sudo apt-get -y install finger pciutils usbutils lshw mc cluster-ssh tree
# 200MB for texlive-latex-base, >800MB after texlive-latex-extra
sudo apt-get -y install texlive-latex-base texlive-latex-extra texlive-bibtex-extra texlive-publishers highlight
sudo apt-get -y install apt-file
sudo apt-get -y install wodim genisoimage
# 1.7GB
sudo apt-get -y install gnome update-manager-gnome apt-watch-gnome
# 533MB
sudo apt-get -y install libreoffice
sudo apt-get -y install flashplugin-nonfree iceweasel
sudo apt-get -y install mplayer2 module-assistant
sudo apt-get -y install vim-gnome nautilus-open-terminal deluge wbar
sudo apt-get -y install gitk xchat pidgin dia
sudo apt-get -y install aspell-ro
sudo apt-get -y install wireless-tools tcpdump nmap
# non-free required
sudo apt-get -y install manpages-posix manpages-posix-dev make-doc glibc-doc-reference
# pwgen
sudo apt-get -y install pwgen
# lshw
sudo apt-get -y install lshw
# emacs, org-mode
sudo apt-get -y install emacs org-mode emacs-goodies-el
sudo apt-get -y install screen tmux
sudo apt-get -y install ethtool net-tools
