#!/bin/bash

sudo /sbin/ip link set dev eth0 down
sudo /sbin/ip address flush dev eth0
sudo /sbin/ip address add 192.168.42.1/24 dev eth0
sudo /sbin/ip link set dev eth0 up
sudo /sbin/ip address del 192.168.42.11/24 dev eth0
sudo /sbin/ip route del default via 192.168.42.1 dev eth0
sudo /sbin/ip link set dev wlan0 down
sudo /sbin/sysctl net.ipv4.ip_forward=1
sudo /sbin/sysctl net.ipv6.conf.default.forwarding=1
sudo /sbin/sysctl net.ipv6.conf.all.forwarding=1
sudo /sbin/iptables -t nat -D POSTROUTING -o ppp0 -j MASQUERADE
sudo /sbin/iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
