#!/bin/bash

sudo dnf install snapd
sudo test -L /snap || sudo ln -sfn /var/lib/snapd/snap /snap
sudo snap install pdftk
sudo dnf install --rpmverbosity=critical -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm
sudo dnf install --rpmverbosity=critical -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm
sudo dnf install --rpmverbosity=critical -y unrar
