#!/bin/bash

private_key=$(echo -e "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIA91xb59+0AMsIVI5WB2A07qmk0aUc+CPftTuI1yVDRf\n-----END PRIVATE KEY-----")
public_key=$(echo -e "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAC3S5qA2LRbPpxYPZZZzbs+k/9inr0spoP5/G7RexZAc=\n-----END PUBLIC KEY-----")
text="loremipsum"
signature=$(echo -e "\x18\x54\x6b\xd2\x0e\x0d\x5e\xc3\x46\xb7\xc1\xc1\x62\xb9\x19\x1b\x51\xa0\xf0\x4a\x06\xfc\xbc\x1b\x7f\x05\x20\x2f\xdf\x54\x3c\xbd\x62\xd9\x79\x97\xff\x8c\xea\x7d\x9a\xdc\x47\x5f\x60\x46\x13\x78\xa6\x5a\xd1\x08\x6e\x6a\xff\x45\x86\x57\xa6\x5e\x16\x23\x24\x07")

./ed25519
./ed25519 s "$test" "$private_key" 10000
./ed25519 v "$text" "$public_key" "$signature" 10000
